/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBridgeRouteImport } from './routes/admin/bridge'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSongsRouteImport } from './routes/admin/songs'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminYoungWolfRouteImport } from './routes/admin/young-wolf'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppLizakiRouteImport } from './routes/app/lizaki'
import { Route as AppNagrodyRouteImport } from './routes/app/nagrody'
import { Route as AppNaukaRouteImport } from './routes/app/nauka'
import { Route as AppNoraRouteImport } from './routes/app/nora'
import { Route as AppPomocRouteImport } from './routes/app/pomoc'
import { Route as AppPowtorkaRouteImport } from './routes/app/powtorka'
import { Route as AppProfilRouteImport } from './routes/app/profil'
import { Route as AppRodzicRouteImport } from './routes/app/rodzic'
import { Route as AppSzkolaRouteImport } from './routes/app/szkola'
import { Route as AppWilkRouteImport } from './routes/app/wilk'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBridgeRoute = AdminBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSongsRoute = AdminSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminYoungWolfRoute = AdminYoungWolfRouteImport.update({
  id: '/young-wolf',
  path: '/young-wolf',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLizakiRoute = AppLizakiRouteImport.update({
  id: '/lizaki',
  path: '/lizaki',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNagrodyRoute = AppNagrodyRouteImport.update({
  id: '/nagrody',
  path: '/nagrody',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNaukaRoute = AppNaukaRouteImport.update({
  id: '/nauka',
  path: '/nauka',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNoraRoute = AppNoraRouteImport.update({
  id: '/nora',
  path: '/nora',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPomocRoute = AppPomocRouteImport.update({
  id: '/pomoc',
  path: '/pomoc',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPowtorkaRoute = AppPowtorkaRouteImport.update({
  id: '/powtorka',
  path: '/powtorka',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRodzicRoute = AppRodzicRouteImport.update({
  id: '/rodzic',
  path: '/rodzic',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSzkolaRoute = AppSzkolaRouteImport.update({
  id: '/szkola',
  path: '/szkola',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWilkRoute = AppWilkRouteImport.update({
  id: '/wilk',
  path: '/wilk',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bridge': typeof AdminBridgeRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/young-wolf': typeof AdminYoungWolfRoute
  '/app/lizaki': typeof AppLizakiRoute
  '/app/nagrody': typeof AppNagrodyRoute
  '/app/nauka': typeof AppNaukaRoute
  '/app/nora': typeof AppNoraRoute
  '/app/pomoc': typeof AppPomocRoute
  '/app/powtorka': typeof AppPowtorkaRoute
  '/app/profil': typeof AppProfilRoute
  '/app/rodzic': typeof AppRodzicRoute
  '/app/szkola': typeof AppSzkolaRoute
  '/app/wilk': typeof AppWilkRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bridge': typeof AdminBridgeRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/young-wolf': typeof AdminYoungWolfRoute
  '/app/lizaki': typeof AppLizakiRoute
  '/app/nagrody': typeof AppNagrodyRoute
  '/app/nauka': typeof AppNaukaRoute
  '/app/nora': typeof AppNoraRoute
  '/app/pomoc': typeof AppPomocRoute
  '/app/powtorka': typeof AppPowtorkaRoute
  '/app/profil': typeof AppProfilRoute
  '/app/rodzic': typeof AppRodzicRoute
  '/app/szkola': typeof AppSzkolaRoute
  '/app/wilk': typeof AppWilkRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/bridge': typeof AdminBridgeRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/songs': typeof AdminSongsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/young-wolf': typeof AdminYoungWolfRoute
  '/app/lizaki': typeof AppLizakiRoute
  '/app/nagrody': typeof AppNagrodyRoute
  '/app/nauka': typeof AppNaukaRoute
  '/app/nora': typeof AppNoraRoute
  '/app/pomoc': typeof AppPomocRoute
  '/app/powtorka': typeof AppPowtorkaRoute
  '/app/profil': typeof AppProfilRoute
  '/app/rodzic': typeof AppRodzicRoute
  '/app/szkola': typeof AppSzkolaRoute
  '/app/wilk': typeof AppWilkRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/admin/bridge'
    | '/admin/content'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/songs'
    | '/admin/users'
    | '/admin/young-wolf'
    | '/app/lizaki'
    | '/app/nagrody'
    | '/app/nauka'
    | '/app/nora'
    | '/app/pomoc'
    | '/app/powtorka'
    | '/app/profil'
    | '/app/rodzic'
    | '/app/szkola'
    | '/app/wilk'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/admin/bridge'
    | '/admin/content'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/songs'
    | '/admin/users'
    | '/admin/young-wolf'
    | '/app/lizaki'
    | '/app/nagrody'
    | '/app/nauka'
    | '/app/nora'
    | '/app/pomoc'
    | '/app/powtorka'
    | '/app/profil'
    | '/app/rodzic'
    | '/app/szkola'
    | '/app/wilk'
    | '/admin'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/admin/bridge'
    | '/admin/content'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/songs'
    | '/admin/users'
    | '/admin/young-wolf'
    | '/app/lizaki'
    | '/app/nagrody'
    | '/app/nauka'
    | '/app/nora'
    | '/app/pomoc'
    | '/app/powtorka'
    | '/app/profil'
    | '/app/rodzic'
    | '/app/szkola'
    | '/app/wilk'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bridge': {
      id: '/admin/bridge'
      path: '/bridge'
      fullPath: '/admin/bridge'
      preLoaderRoute: typeof AdminBridgeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/songs': {
      id: '/admin/songs'
      path: '/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/young-wolf': {
      id: '/admin/young-wolf'
      path: '/young-wolf'
      fullPath: '/admin/young-wolf'
      preLoaderRoute: typeof AdminYoungWolfRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lizaki': {
      id: '/app/lizaki'
      path: '/lizaki'
      fullPath: '/app/lizaki'
      preLoaderRoute: typeof AppLizakiRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/nagrody': {
      id: '/app/nagrody'
      path: '/nagrody'
      fullPath: '/app/nagrody'
      preLoaderRoute: typeof AppNagrodyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/nauka': {
      id: '/app/nauka'
      path: '/nauka'
      fullPath: '/app/nauka'
      preLoaderRoute: typeof AppNaukaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/nora': {
      id: '/app/nora'
      path: '/nora'
      fullPath: '/app/nora'
      preLoaderRoute: typeof AppNoraRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pomoc': {
      id: '/app/pomoc'
      path: '/pomoc'
      fullPath: '/app/pomoc'
      preLoaderRoute: typeof AppPomocRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/powtorka': {
      id: '/app/powtorka'
      path: '/powtorka'
      fullPath: '/app/powtorka'
      preLoaderRoute: typeof AppPowtorkaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rodzic': {
      id: '/app/rodzic'
      path: '/rodzic'
      fullPath: '/app/rodzic'
      preLoaderRoute: typeof AppRodzicRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/szkola': {
      id: '/app/szkola'
      path: '/szkola'
      fullPath: '/app/szkola'
      preLoaderRoute: typeof AppSzkolaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/wilk': {
      id: '/app/wilk'
      path: '/wilk'
      fullPath: '/app/wilk'
      preLoaderRoute: typeof AppWilkRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBridgeRoute: typeof AdminBridgeRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSongsRoute: typeof AdminSongsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminYoungWolfRoute: typeof AdminYoungWolfRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBridgeRoute: AdminBridgeRoute,
  AdminContentRoute: AdminContentRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSongsRoute: AdminSongsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminYoungWolfRoute: AdminYoungWolfRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppLizakiRoute: typeof AppLizakiRoute
  AppNagrodyRoute: typeof AppNagrodyRoute
  AppNaukaRoute: typeof AppNaukaRoute
  AppNoraRoute: typeof AppNoraRoute
  AppPomocRoute: typeof AppPomocRoute
  AppPowtorkaRoute: typeof AppPowtorkaRoute
  AppProfilRoute: typeof AppProfilRoute
  AppRodzicRoute: typeof AppRodzicRoute
  AppSzkolaRoute: typeof AppSzkolaRoute
  AppWilkRoute: typeof AppWilkRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppLizakiRoute: AppLizakiRoute,
  AppNagrodyRoute: AppNagrodyRoute,
  AppNaukaRoute: AppNaukaRoute,
  AppNoraRoute: AppNoraRoute,
  AppPomocRoute: AppPomocRoute,
  AppPowtorkaRoute: AppPowtorkaRoute,
  AppProfilRoute: AppProfilRoute,
  AppRodzicRoute: AppRodzicRoute,
  AppSzkolaRoute: AppSzkolaRoute,
  AppWilkRoute: AppWilkRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
